version: '3.5'

networks:
  app_network:
    name: app_network
    driver: bridge

services:

  php:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: ./php
    networks:
      - app_network
    ports:
      - ${PHP_PORT:-9000}:9000
    volumes:
      - ./${SOURCE_DIRECTORY_NAME}:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:latest
    networks:
      - app_network
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./${SOURCE_DIRECTORY_NAME}:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.7
    networks:
      - app_network
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:latest
    networks:
      - app_network
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - REDIS_REPLICATION_MODE=master
